// <auto-generated />
using System;
using ClickableGameBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClickableGameBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240915132713_newmigration6")]
    partial class newmigration6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClickableGameBackend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "M16 Rifle",
                            Power = 30,
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Name = "AK-47",
                            Power = 35,
                            Price = 700m
                        },
                        new
                        {
                            Id = 3,
                            Name = "HK416",
                            Power = 38,
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Name = "FN SCAR",
                            Power = 40,
                            Price = 3000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Barrett M82",
                            Power = 50,
                            Price = 10000m
                        },
                        new
                        {
                            Id = 6,
                            Name = "RPG-7",
                            Power = 45,
                            Price = 1200m
                        },
                        new
                        {
                            Id = 7,
                            Name = "M4 Carbine",
                            Power = 35,
                            Price = 1500m
                        },
                        new
                        {
                            Id = 8,
                            Name = "FN F2000",
                            Power = 38,
                            Price = 2300m
                        },
                        new
                        {
                            Id = 9,
                            Name = "IWI Tavor",
                            Power = 40,
                            Price = 2800m
                        },
                        new
                        {
                            Id = 10,
                            Name = "CZ BREN 2",
                            Power = 38,
                            Price = 2200m
                        },
                        new
                        {
                            Id = 11,
                            Name = "M2 Browning",
                            Power = 50,
                            Price = 12000m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Desert Eagle",
                            Power = 25,
                            Price = 1800m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Glock 17",
                            Power = 20,
                            Price = 600m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Colt M1911",
                            Power = 22,
                            Price = 800m
                        },
                        new
                        {
                            Id = 15,
                            Name = "M1 Abrams",
                            Power = 90,
                            Price = 7000000m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Leopard 2A7",
                            Power = 92,
                            Price = 8000000m
                        },
                        new
                        {
                            Id = 17,
                            Name = "T-90",
                            Power = 85,
                            Price = 4000000m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Challenger 2",
                            Power = 88,
                            Price = 6000000m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Merkava Mk IV",
                            Power = 85,
                            Price = 6500000m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Type 99",
                            Power = 84,
                            Price = 5000000m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Leclerc",
                            Power = 87,
                            Price = 9000000m
                        },
                        new
                        {
                            Id = 22,
                            Name = "K2 Black Panther",
                            Power = 90,
                            Price = 8500000m
                        },
                        new
                        {
                            Id = 23,
                            Name = "T-14 Armata",
                            Power = 92,
                            Price = 7500000m
                        },
                        new
                        {
                            Id = 24,
                            Name = "AMX-56 Leclerc",
                            Power = 88,
                            Price = 8500000m
                        },
                        new
                        {
                            Id = 25,
                            Name = "PT-91 Twardy",
                            Power = 80,
                            Price = 4500000m
                        },
                        new
                        {
                            Id = 26,
                            Name = "F-35 Lightning II",
                            Power = 95,
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Sukhoi Su-57",
                            Power = 90,
                            Price = 90000000m
                        },
                        new
                        {
                            Id = 28,
                            Name = "F-22 Raptor",
                            Power = 98,
                            Price = 120000000m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Eurofighter Typhoon",
                            Power = 85,
                            Price = 80000000m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Dassault Rafale",
                            Power = 84,
                            Price = 75000000m
                        },
                        new
                        {
                            Id = 31,
                            Name = "J-20 Mighty Dragon",
                            Power = 88,
                            Price = 90000000m
                        },
                        new
                        {
                            Id = 32,
                            Name = "Saab Gripen",
                            Power = 80,
                            Price = 60000000m
                        },
                        new
                        {
                            Id = 33,
                            Name = "F/A-18 Super Hornet",
                            Power = 87,
                            Price = 75000000m
                        },
                        new
                        {
                            Id = 34,
                            Name = "MiG-35",
                            Power = 82,
                            Price = 45000000m
                        },
                        new
                        {
                            Id = 35,
                            Name = "F-16 Fighting Falcon",
                            Power = 80,
                            Price = 40000000m
                        },
                        new
                        {
                            Id = 36,
                            Name = "F-15 Eagle",
                            Power = 85,
                            Price = 60000000m
                        },
                        new
                        {
                            Id = 37,
                            Name = "Su-35 Flanker-E",
                            Power = 85,
                            Price = 50000000m
                        },
                        new
                        {
                            Id = 38,
                            Name = "A-10 Thunderbolt II",
                            Power = 70,
                            Price = 18000000m
                        },
                        new
                        {
                            Id = 39,
                            Name = "B-2 Spirit Bomber",
                            Power = 98,
                            Price = 1500000000m
                        },
                        new
                        {
                            Id = 40,
                            Name = "B-52 Stratofortress",
                            Power = 85,
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 41,
                            Name = "Arleigh Burke Destroyer",
                            Power = 80,
                            Price = 1500000000m
                        },
                        new
                        {
                            Id = 42,
                            Name = "Zumwalt-Class Destroyer",
                            Power = 85,
                            Price = 4000000000m
                        },
                        new
                        {
                            Id = 43,
                            Name = "Nimitz-Class Aircraft Carrier",
                            Power = 98,
                            Price = 9000000000m
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ford-Class Aircraft Carrier",
                            Power = 100,
                            Price = 13000000000m
                        },
                        new
                        {
                            Id = 45,
                            Name = "Queen Elizabeth-Class Carrier",
                            Power = 95,
                            Price = 6500000000m
                        },
                        new
                        {
                            Id = 46,
                            Name = "Type 45 Destroyer",
                            Power = 80,
                            Price = 1200000000m
                        },
                        new
                        {
                            Id = 47,
                            Name = "Admiral Gorshkov-Class Frigate",
                            Power = 75,
                            Price = 500000000m
                        },
                        new
                        {
                            Id = 48,
                            Name = "LCS Freedom-Class",
                            Power = 70,
                            Price = 400000000m
                        },
                        new
                        {
                            Id = 49,
                            Name = "Seawolf-Class Submarine",
                            Power = 95,
                            Price = 3000000000m
                        },
                        new
                        {
                            Id = 50,
                            Name = "Virginia-Class Submarine",
                            Power = 90,
                            Price = 2700000000m
                        });
                });

            modelBuilder.Entity("ClickableGameBackend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId1");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBalances");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.Transaction", b =>
                {
                    b.HasOne("ClickableGameBackend.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClickableGameBackend.Models.Item", null)
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId1");

                    b.HasOne("ClickableGameBackend.Models.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserBalance", b =>
                {
                    b.HasOne("ClickableGameBackend.Models.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("ClickableGameBackend.Models.UserBalance", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserItem", b =>
                {
                    b.HasOne("ClickableGameBackend.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickableGameBackend.Models.User", null)
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClickableGameBackend.Models.Item", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.User", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("UserBalance");

                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
