// <auto-generated />
using System;
using ClickableGameBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClickableGameBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240920145527_newItemPowers")]
    partial class newItemPowers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClickableGameBackend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Power")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://www.tacticool22.com/wp-content/uploads/2015/12/colt-m16-22-left.jpg",
                            Name = "M16 Rifle",
                            Power = 0.3m,
                            Price = 1200m
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.proarmis.si/product_images/l/ak47_7.62x39_wbp_jack_wood_premium_2.jpg",
                            Name = "AK-47",
                            Power = 0.35m,
                            Price = 700m
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://hk-usa.com/wp-content/uploads/1-HK416-10.4-LEFT1.jpg",
                            Name = "HK416",
                            Power = 0.4m,
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://fnamerica.com/wp-content/uploads/2016/12/SCAR-17S-FDE_026.jpg",
                            Name = "FN SCAR",
                            Power = 0.45m,
                            Price = 3000m
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/5a/Barrett-M82A1-Independence-Day-2017-IZE-048-white.jpg",
                            Name = "Barrett M82",
                            Power = 0.6m,
                            Price = 10000m
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://www.prc68.com/I/Images/RPG7-12b.jpg",
                            Name = "RPG-7",
                            Power = 5m,
                            Price = 1200m
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://gunsweek.com/sites/default/files/styles/content_sm/public/archive/contents/rifles/articles/colt-defense-m4-classic-series/Colt_M4_Classic_Series_23.JPG?itok=_UD1C2Un",
                            Name = "M4 Carbine",
                            Power = 0.35m,
                            Price = 1500m
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://slovarms.si/media/catalog/product/cache/1/small_image/1200x630/9df78eab33525d08d6e5fb8d27136e95/f/n/fn_2000.jpg",
                            Name = "FN F2000",
                            Power = 0.4m,
                            Price = 2300m
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d7/IWI-Tavor-TAR-21w1.jpg",
                            Name = "IWI Tavor",
                            Power = 0.45m,
                            Price = 2800m
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://gunsweek.com/sites/default/files/archive/contents/rifles/news/cz-bren-2-br-762x51mm-battle-rifle/CZ-BREN2-BR-Icon.jpg",
                            Name = "CZ BREN 2",
                            Power = 0.4m,
                            Price = 2200m
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/PEO_Browning_M2E2_QCB_%28c1%29.jpg/1200px-PEO_Browning_M2E2_QCB_%28c1%29.jpg",
                            Name = "M2 Browning",
                            Power = 8m,
                            Price = 12000m
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://cdn11.bigcommerce.com/s-kp97pt369w/images/stencil/1280x1280/products/2169/4939/SVimg-DE50SRMB__97561.1515511754.jpg?c=2",
                            Name = "Desert Eagle",
                            Power = 0.2m,
                            Price = 1800m
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://slovarms.si/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/g/l/glock-17-gen-5_1.jpg",
                            Name = "Glock 17",
                            Power = 0.1m,
                            Price = 600m
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://www.colt.com/wp-content/uploads/2022/12/1911-classic-.45.jpg",
                            Name = "Colt M1911",
                            Power = 0.15m,
                            Price = 800m
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Abrams-transparent.png/1200px-Abrams-transparent.png",
                            Name = "M1 Abrams",
                            Power = 60m,
                            Price = 7000000m
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://www.modellbahnunion.com/modellbahn-union-en/prodpic/HO-Tank-Leopard-2A7-FRG-Artitec-6870671_b_0.JPG",
                            Name = "Leopard 2A7",
                            Power = 65m,
                            Price = 8000000m
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://www.technic-toys.com/wp-content/uploads/2022/04/23118-600x344.jpg",
                            Name = "T-90",
                            Power = 55m,
                            Price = 4000000m
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://www.super-hobby.si/zdjecia/0/8/5/277_rd.jpg",
                            Name = "Challenger 2",
                            Power = 58m,
                            Price = 6000000m
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://www.torro-shop.de/media/image/product/12211/lg/1-16-rc-idf-merkava-mk-iv-bbir.jpg",
                            Name = "Merkava Mk IV",
                            Power = 55m,
                            Price = 6500000m
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://static.wikia.nocookie.net/armoredwarfare_gamepedia/images/b/b5/400px_Type_99.png/revision/latest?cb=20220602113420",
                            Name = "Type 99",
                            Power = 54m,
                            Price = 5000000m
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://static.wikia.nocookie.net/armoredwarfare_gamepedia/images/c/c7/400px_Leclerc.png/revision/latest?cb=20220209061434",
                            Name = "Leclerc",
                            Power = 57m,
                            Price = 9000000m
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://static.wikia.nocookie.net/armoredwarfare_gamepedia/images/f/f3/K2_Black_Panther_K2PL_skin_icon.png/revision/latest?cb=20221102171501",
                            Name = "K2 Black Panther",
                            Power = 60m,
                            Price = 8500000m
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://static.wikia.nocookie.net/armoredwarfare_gamepedia/images/5/56/400px_T-14_Armata.png/revision/latest?cb=20220209073631",
                            Name = "T-14 Armata",
                            Power = 65m,
                            Price = 7500000m
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://p.turbosquid.com/ts-thumb/Rs/VRdg1E/JK/amx_56_leclerc_french_main_battle_tank_rigged_002/jpg/1674133615/600x600/fit_q87/c581b01b01a3c245e43fed4751b2f63220349ebf/amx_56_leclerc_french_main_battle_tank_rigged_002.jpg",
                            Name = "AMX-56 Leclerc",
                            Power = 58m,
                            Price = 8500000m
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://360view.hum3d.com/standard/Tanks/PT-91_Twardy_360_720_50-35.jpg",
                            Name = "PT-91 Twardy",
                            Power = 50m,
                            Price = 4500000m
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/b/bf/Testflyging_av_f%C3%B8rste_norske_F-35_-1_%28cropped%29.jpg",
                            Name = "F-35 Lightning II",
                            Power = 400m,
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://static1.simpleflyingimages.com/wordpress/wp-content/uploads/2024/02/shutterstock_2176703295-1.jpg",
                            Name = "Sukhoi Su-57",
                            Power = 380m,
                            Price = 90000000m
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/F-22_Raptor_edit1_%28cropped%29.jpg/1200px-F-22_Raptor_edit1_%28cropped%29.jpg",
                            Name = "F-22 Raptor",
                            Power = 450m,
                            Price = 120000000m
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0360/4209/t/49/assets/eurofighter_typhoon_aut-1693194083159.jpg?v=1693194084",
                            Name = "Eurofighter Typhoon",
                            Power = 350m,
                            Price = 80000000m
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://i0.wp.com/militaryleak.com/wp-content/uploads/2024/01/indonesian-air-force-completes-acquisition-of-42-dassault-rafale-fighter-jets.jpg",
                            Name = "Dassault Rafale",
                            Power = 320m,
                            Price = 75000000m
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/73/J-20_at_CCAS2022_%2820220827103424%29.jpg",
                            Name = "J-20 Mighty Dragon",
                            Power = 370m,
                            Price = 90000000m
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Saab_JAS_39_Gripen_at_Kaivopuisto_Air_Show%2C_June_2017_%28altered%29_copy.jpg/1200px-Saab_JAS_39_Gripen_at_Kaivopuisto_Air_Show%2C_June_2017_%28altered%29_copy.jpg",
                            Name = "Saab Gripen",
                            Power = 300m,
                            Price = 60000000m
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/d/de/US_Navy_071203-N-8923M-074_An_F-A-18F_Super_Hornet%2C_from_the_Red_Rippers_of_Strike_Fighter_Squadron_%28VFA%29_11%2C_makes_a_sharp_turn_above_the_flight_deck_aboard_the_Nimitz-class_nuclear-powered_aircraft_carrier_USS_Harry_S._Truman.jpg",
                            Name = "F/A-18 Super Hornet",
                            Power = 330m,
                            Price = 75000000m
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "https://img.goodfon.com/original/2560x1662/d/53/mig-35-samoliot-oruzhie.jpg",
                            Name = "MiG-35",
                            Power = 310m,
                            Price = 45000000m
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "https://d.newsweek.com/en/full/2386052/falcon-fighter-india.jpg?w=1600&h=1200&q=88&f=8d07b013bcff347223f2e065e5edc4ef",
                            Name = "F-16 Fighting Falcon",
                            Power = 310m,
                            Price = 40000000m
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a6/F-15C_Eagle_from_the_44th_Fighter_Squadron_flies_during_a_routine_training_exercise_April_15%2C_2019.jpg",
                            Name = "F-15 Eagle",
                            Power = 340m,
                            Price = 60000000m
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ec/Russian_Air_Force%2C_RF-81719%2C_Sukhoi_Su-35S_%2849581740157%29.jpg",
                            Name = "Su-35 Flanker-E",
                            Power = 330m,
                            Price = 50000000m
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/cf/A-10_Thunderbolt_II_In-flight-2.jpg",
                            Name = "A-10 Thunderbolt II",
                            Power = 280m,
                            Price = 18000000m
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/B-2_Spirits_on_Deployment_to_Indo-Asia-Pacific.jpg/640px-B-2_Spirits_on_Deployment_to_Indo-Asia-Pacific.jpg",
                            Name = "B-2 Spirit Bomber",
                            Power = 500m,
                            Price = 1500000000m
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "https://cloudfront-us-east-1.images.arcpublishing.com/archetype/DJED4KFT4VDDRI35Y5BC2SKXSM.jpg",
                            Name = "B-52 Stratofortress",
                            Power = 400m,
                            Price = 100000000m
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "https://www.naval-technology.com/wp-content/uploads/sites/15/2022/05/DDG-121-scaled.jpg",
                            Name = "Arleigh Burke Destroyer",
                            Power = 2000m,
                            Price = 1500000000m
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/43/160421-N-YE579-005_%2826543438313%29.jpg",
                            Name = "Zumwalt-Class Destroyer",
                            Power = 2500m,
                            Price = 4000000000m
                        },
                        new
                        {
                            Id = 43,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/81/USS_Nimitz_in_Victoria_Canada_036.jpg",
                            Name = "Nimitz-Class Aircraft Carrier",
                            Power = 20000m,
                            Price = 9000000000m
                        },
                        new
                        {
                            Id = 44,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/52/USS_Gerald_R._Ford_%28CVN-78%29_underway_in_the_Atlantic_Ocean_on_9_October_2022_%28221009-N-TL968-1248%29.JPG",
                            Name = "Ford-Class Aircraft Carrier",
                            Power = 25000m,
                            Price = 13000000000m
                        },
                        new
                        {
                            Id = 45,
                            ImageUrl = "https://www.seaforces.org/marint/Royal-Navy/Aircraft-Carrier/R08-HMS-Queen-Elizabeth_DAT/R08-HMS-Queen-Elizabeth-084.jpg",
                            Name = "Queen Elizabeth-Class Carrier",
                            Power = 15000m,
                            Price = 6500000000m
                        },
                        new
                        {
                            Id = 46,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/b/bf/HMS_Daring-1.jpg",
                            Name = "Type 45 Destroyer",
                            Power = 1800m,
                            Price = 1200000000m
                        },
                        new
                        {
                            Id = 47,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Admiral_Gorshkov_frigate_02.jpg/800px-Admiral_Gorshkov_frigate_02.jpg",
                            Name = "Admiral Gorshkov-Class Frigate",
                            Power = 1500m,
                            Price = 500000000m
                        },
                        new
                        {
                            Id = 48,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/0/0a/USS-Freedom-130222-N-DR144-174-crop.jpg",
                            Name = "LCS Freedom-Class",
                            Power = 1200m,
                            Price = 400000000m
                        },
                        new
                        {
                            Id = 49,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Defense.gov_News_Photo_960703-N-00000-001.jpg/1200px-Defense.gov_News_Photo_960703-N-00000-001.jpg",
                            Name = "Seawolf-Class Submarine",
                            Power = 4000m,
                            Price = 3000000000m
                        },
                        new
                        {
                            Id = 50,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/b/bb/US_Navy_040730-N-1234E-002_PCU_Virginia_%28SSN_774%29_returns_to_the_General_Dynamics_Electric_Boat_shipyard.jpg",
                            Name = "Virginia-Class Submarine",
                            Power = 3500m,
                            Price = 2700000000m
                        });
                });

            modelBuilder.Entity("ClickableGameBackend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId1");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBalances");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Power")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.Transaction", b =>
                {
                    b.HasOne("ClickableGameBackend.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClickableGameBackend.Models.Item", null)
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId1");

                    b.HasOne("ClickableGameBackend.Models.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserBalance", b =>
                {
                    b.HasOne("ClickableGameBackend.Models.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("ClickableGameBackend.Models.UserBalance", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.UserItem", b =>
                {
                    b.HasOne("ClickableGameBackend.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickableGameBackend.Models.User", null)
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClickableGameBackend.Models.Item", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClickableGameBackend.Models.User", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("UserBalance");

                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
